# Generated by Django 4.2.6 on 2023-11-03 21:41
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, 
                                           primary_key=True, 
                                           serialize=False, 
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.TextField(blank=True)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('money', models.BooleanField(default=False)),
            ],
        ),
    ]
