# Generated by Django 4.2.6 on 2023-12-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studens',
            old_name='money',
            new_name='scholarship',
        ),
        migrations.AddField(
            model_name='studens',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studens',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studens',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
