# Generated by Django 4.2.6 on 2023-12-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studens_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studens',
            name='scholarship',
            field=models.BooleanField(default=True),
        ),
    ]
