# Generated by Django 4.2.6 on 2023-12-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_category_studens_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='studens',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studens',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
