# Generated by Django 4.2.6 on 2023-12-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studens_time_create_studens_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studens',
            name='scholarship',
            field=models.BooleanField(),
        ),
    ]
