# Generated by Django 4.2.6 on 2023-12-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_studens_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studens',
            name='scholarship',
            field=models.BooleanField(null=True),
        ),
    ]
